apiVersion: v1
kind: Secret
metadata:
  name: freeradius-server
  namespace: default
type: Opaque
stringData:
  clients.conf: |
    client all-network {
      ipaddr		= 0.0.0.0/0
      secret		= YOUR_SECRET
    }
  ca.pem: |
    YOUR_CERT
  server.pem: |
    YOUR_KEY

