apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-server
  namespace: default
  labels:
    app: freeradius-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeradius-server
  template:
    metadata:
      labels:
        app: freeradius-server
    spec:
      securityContext:
          fsGroup: 101    
      containers:
      - name: freeradius-server
        image: freeradius/freeradius-server:3.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1812
          protocol: UDP
          name: auth
        - containerPort: 1813
          protocol: UDP
          name: acct
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512M    
        volumeMounts:
        - name: config
          mountPath: /etc/raddb/radiusd.conf
          subPath: radiusd.conf
        - name: secret
          mountPath: /etc/raddb/clients.conf
          subPath: clients.conf          
        - name: config
          mountPath: /etc/raddb/sites-available/default
          subPath: default
        - name: config
          mountPath: /etc/raddb/sites-available/inner-tunnel
          subPath: inner-tunnel
        - name: config
          mountPath: /etc/raddb/mods-available/sql
          subPath: sql     
        - name: config
          mountPath: /etc/raddb/mods-enabled/sql
          subPath: sql
        - mountPath: /etc/raddb/certs/server.pem
          name: secret
          subPath: server.pem
        - mountPath: /etc/raddb/certs/ca.pem
          name: secret
          subPath: ca.pem                                     
      volumes:
      - name: config
        configMap:
          name: freeradius-server       
      - name: secret
        secret:
          secretName: freeradius-server                     

