apiVersion: v1
kind: Secret
metadata:
  name: freeradius-server
  namespace: default
type: Opaque
stringData:
  clients.conf: |
    client all-network {
      ipaddr		= 0.0.0.0/0
      secret		= 1234567890
    }
