services:
  freeradius-server:
    container_name: freeradius-server
    restart: always
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    build:
      context: "."
    environment:
    - TZ=Asia/Taipei
