apiVersion: v1
kind: Secret
metadata:
  name: freeradius-server-secret
type: Opaque
stringData:
  clients.conf: |
    client all-network {
           ipaddr          = 0.0.0.0/0
           secret          = 1234567890
    }    