apiVersion: v1
data:
  radiusd.conf: |
    prefix = /usr
    exec_prefix = /usr
    sysconfdir = /etc
    localstatedir = /var
    sbindir = ${exec_prefix}/sbin
    logdir = /var/log/freeradius
    raddbdir = /etc/freeradius
    radacctdir = ${logdir}/radacct
    name = freeradius
    confdir = ${raddbdir}
    modconfdir = ${confdir}/mods-config
    certdir = ${confdir}/certs
    cadir   = ${confdir}/certs
    run_dir = ${localstatedir}/run/${name}
    db_dir = ${raddbdir}
    libdir = /usr/lib/freeradius
    pidfile = ${run_dir}/${name}.pid
    correct_escapes = true
    max_request_time = 30
    cleanup_delay = 5
    max_requests = 16384
    hostname_lookups = no

    log {
            destination = files
            colourise = yes
            file = ${logdir}/radius.log
            syslog_facility = daemon
            stripped_names = no
            auth = yes
            auth_accept = yes
            auth_reject = yes
            auth_badpass = no
            auth_goodpass = no
            msg_denied = "You are already logged in - access denied"
    }

    checkrad = ${sbindir}/checkrad

    ENV {

    }

    security {
            user = freerad
            group = freerad
            allow_core_dumps = no
            max_attributes = 200
            reject_delay = 1
            status_server = yes
    }

    proxy_requests  = yes
    $INCLUDE proxy.conf
    $INCLUDE clients.conf

    thread pool {
            start_servers = 5
            max_servers = 32
            min_spare_servers = 3
            max_spare_servers = 10
            max_requests_per_server = 0
            auto_limit_acct = no
    }

    modules {
            $INCLUDE mods-enabled/
    }

    instantiate {

    }

    policy {
            $INCLUDE policy.d/
    }

    $INCLUDE sites-enabled/
  eap: |
    eap {
            default_eap_type = md5
            timer_expire = 60
            ignore_unknown_eap_types = no
            cisco_accounting_username_bug = no
            max_sessions = ${max_requests}

            md5 {

            }

            gtc {
                    auth_type = PAP
            }

            tls-config tls-common {
                    private_key_password = whatever
                    private_key_file = ${certdir}/server.pem
                    certificate_file = ${certdir}/server.pem
                    ca_file = ${cadir}/ca.pem
                    dh_file = ${certdir}/dh
                    ca_path = ${cadir}
                    cipher_list = "DEFAULT@SECLEVEL=1"
                    cipher_server_preference = no
                    tls_min_version = "1.0"
                    tls_max_version = "1.2"
                    ecdh_curve = "prime256v1"

                    cache {
                            enable = no

                            store {
                                    Tunnel-Private-Group-Id
                            }
                    }

                    verify {

                    }

                    ocsp {
                            enable = no
                            override_cert_url = yes
                            url = "http://127.0.0.1/ocsp/"
                    }
            }
            tls {
                    tls = tls-common
            }

            ttls {
                    tls = tls-common
                    default_eap_type = md5
                    copy_request_to_tunnel = no
                    use_tunneled_reply = no
                    virtual_server = "inner-tunnel"
            }

            peap {
                    tls = tls-common
                    default_eap_type = mschapv2
                    copy_request_to_tunnel = no
                    use_tunneled_reply = no
                    virtual_server = "inner-tunnel"
            }

            mschapv2 {
              
            }
    }
kind: ConfigMap
metadata:
  name: freeradius-server-config
  namespace: default
