apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-server-deployment
  labels:
    app: freeradius-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeradius-server
  template:
    metadata:
      labels:
        app: freeradius-server
    spec:
      containers:
      - name: freeradius-server
        image: freeradius/freeradius-server
        ports:
        - containerPort: 1812
          protocol: UDP
          name: auth
        - containerPort: 1813
          protocol: UDP
          name: acct
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/freeradius/mods-config/files/authorize
          subPath: authorize
        - name: secret-volume
          mountPath: /etc/freeradius/clients.conf
          subPath: clients.conf
        - name: config-volume
          mountPath: /etc/freeradius/radiusd.conf
          subPath: radiusd.conf
        - name: secret-volume
          mountPath: /etc/freeradius/certs/server.pem
          subPath: server.pem
        - name: secret-volume
          mountPath: /etc/freeradius/certs/server.crt
          subPath: server.crt
      volumes:
      - name: config-volume
        configMap:
          name: freeradius-server-config
      - name: secret-volume
        secret:
          secretName: freeradius-server-secret
