apiVersion: v1
data:
  authorize: |
    DEFAULT Framed-Protocol == PPP
            Framed-Protocol = PPP,
            Framed-Compression = Van-Jacobson-TCP-IP

    DEFAULT Hint == "CSLIP"
            Framed-Protocol = SLIP,
            Framed-Compression = Van-Jacobson-TCP-IP

    DEFAULT Hint == "SLIP"
            Framed-Protocol = SLIP

    user01    Cleartext-Password := "user01"
           Reply-Message := "Hello, %{User-Name}"

    user02    Cleartext-Password := "user02"
           Reply-Message := "Hello, %{User-Name}"

    user03    Cleartext-Password := "user03"
           Reply-Message := "Hello, %{User-Name}"
  clients.conf: |
    client all-network {
           ipaddr          = 0.0.0.0/0
           secret          = 1234567890
    }           
kind: ConfigMap
metadata:
  name: freeradius-server-config
  namespace: default
