apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-server
  labels:
    app: freeradius-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeradius-server
  template:
    metadata:
      labels:
        app: freeradius-server
    spec:
      containers:
      - name: freeradius-server
        image: freeradius/freeradius-server:3.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1812
          protocol: UDP
          name: auth
        - containerPort: 1813
          protocol: UDP
          name: acct
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512M          

