# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mariadb-radius
    image: mariadb-radius:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb1234
    ports:
      - 3306:3306
  adminer:
    container_name: adminer-mariadb
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
