apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-server
  labels:
    app: freeradius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeradius
  template:
    metadata:
      labels:
        app: freeradius
    spec:
      containers:
        - name: freeradius-server
          image: dogkeeper886/freeradius-server:0.091
          ports:
            - name: auth
              containerPort: 1812
              protocol: UDP
            - name: acct
              containerPort: 1813
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: freeradius-service
spec:
  selector:
    app: freeradius
  ports:
    - name: auth
      port: 1812
      protocol: UDP
    - name: acct
      port: 1813
      protocol: UDP
  type: NodePort
